---
bibliography: references.bib
---

# Replicating "Behavioral responses across a mosaic of ecosystem states restructure a sea otter-urchin trophic cascade" by Smith et al, 2021.

Team members: Nikka Malakooti, Andrea Paz-Lacavex, Maddie Mcnelis, Cecilia Girvin.

### Objective

This document is our Final Project for BIOE215 Data Science. This activity has the objective of applying learned techniques to set up a computational analysis (using RStudio, git, and GitHub) and techniques for analyzing data (creating and accessing data structures, writing functions, and using the tidyverse). We have applied those skills to replicate Figure 2 (a and b) from [@smith2021].

For the purpose of this exercise, Andrea will be the Repository Maintainer in the following GitHub Repository: <https://github.com/andreapazlacavex/BIOE215FinalProjectTrophicCascade>

------------------------------------------------------------------------

### Data adquisition

Data retrieved from Dryad are linked [here](https://datadryad.org/stash/dataset/doi:10.7291/D1566H).

Description of data and metadata are linked [here](data.md).

------------------------------------------------------------------------

### **Computational analysis to replicate a key finding**

In order to replicate Figure 2a and 2b from [@smith2021] the following workflow has been planned for per figure

#### Figure 2a

1.  

#### Figure 2b

1.  
